config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  root to: 'pages#home'
  get '/posts/:id', to: 'pages#show', :as => :posts
  get "/fetch_posts" => 'pages#from_tag', as: 'fetch_posts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :forest do
    post '/actions/moderate-comment' => 'comments#moderate_comment'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_and_belongs_to_many :tags
  has_many :comments
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class Forest::CommentsController < ForestLiana::ApplicationController
  def moderate_comment
    # Your business logic to send an email here.
    p params
    render json: { success: 'Hello sandro' }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @posts = Post.all
    @tags = Tag.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def from_tag
    @selected = Post.joins(:tags).where(tags: { id: params[:tag_id] })
      respond_to do |format|
        format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/from_tag.js.erb
$("#posts_grid").html("<%= j render 'shared/posts_list', posts: @selected %>");

app/views/pages/home.html.erb
<div class="container">

  <h1>L'étagère digitale</h1>

  <%= render 'shared/filter_menu' %>

  <%= render partial: 'shared/post_grid', posts: @posts %>

</div>

app/views/pages/show.html.erb
<div class="container">
  <div class="col-xs-12">
    <h1><%= @post.title %></h1>
    <p><%= @post.body %></p>
  </div>
</div>

app/views/shared/_filter_menu.html.erb
  <div class="filters">
    <% @tags.each do |tag| %>
    <div class="filter btn-medium">
      <%= link_to "#{tag.name}", fetch_posts_path(:tag_id => tag.id), :remote => true %>
    </div>
    <% end %>
  </div>

app/views/shared/_post_grid.html.erb
  <div id="posts_grid" class="row">
    <%= render partial: 'shared/posts_list', posts: @posts %>
  </div>

app/views/shared/_posts_list.html.erb
<% @posts.each do |post| %>
<div class="col-xs-12 col-sm-4">
  <%= link_to posts_path(post) do %>
  <div class="card">
    <div class="card-category"><%= post.tags.first.name %></div>
    <div class="card-description">
      <h2><%= post.title %></h2>
    </div>
    <img class="card-user avatar">
  </div>
  <% end %>
</div>
<% end %>